const fs = require('fs');
const path = require('path');

// Bundle/App Group identifiers are read from env vars (set as GitHub Actions
// secrets/variables in CI) rather than hardcoded, since whoever builds this
// needs to register these under their own Apple ID on the free developer
// portal. Sensible local-dev defaults are provided as fallbacks.
const IOS_BUNDLE_IDENTIFIER = process.env.IOS_BUNDLE_IDENTIFIER || 'com.prayermv.app';
const IOS_APP_GROUP_ID = process.env.IOS_APP_GROUP_ID || `group.${IOS_BUNDLE_IDENTIFIER}`;
const ANDROID_PACKAGE = process.env.ANDROID_PACKAGE || 'com.prayermv.app';
const APPLE_TEAM_ID = process.env.APPLE_TEAM_ID || undefined;

// See assets/sounds/README.md - the actual adhan.wav isn't committed yet,
// so this only gets added to the notifications plugin (which would
// otherwise fail the prebuild trying to copy a file that doesn't exist)
// once someone actually drops it in.
const ADHAN_SOUND_RELATIVE_PATH = './assets/sounds/adhan.wav';
const adhanSoundExists = fs.existsSync(path.join(__dirname, 'assets/sounds/adhan.wav'));

// The widget needs this same App Group id compiled in natively so it can
// open the same UserDefaults suite the app writes its selected island to
// (see lib/widgetSync.ts / targets/widget/PrayerData.swift's
// appSelectedIslandId()) - Swift can't read this JS-side env-derived
// constant any other way, since IOS_APP_GROUP_ID varies per builder's own
// Apple ID. Regenerated on every config read (prebuild/start/export/CI), so
// it can't drift from the entitlement below; not committed (see .gitignore).
fs.writeFileSync(
  path.join(__dirname, 'targets/widget/AppGroupConfig.generated.swift'),
  `// GENERATED by app.config.js from IOS_APP_GROUP_ID - do not edit by hand.\nenum AppGroupConfig {\n    static let identifier = "${IOS_APP_GROUP_ID}"\n}\n`
);

/** @type {import('expo/config').ExpoConfig} */
module.exports = {
  expo: {
    name: 'Noor+',
    slug: 'prayermv',
    version: '1.0.0',
    scheme: 'prayermv',
    orientation: 'portrait',
    icon: './assets/icon.png',
    // 'automatic' rather than a fixed 'dark' now that the app itself has a
    // real Light/Dark/System Appearance setting (Settings > Appearance) -
    // this only affects native OS-level chrome (keyboard appearance,
    // system alerts), not the app's own screens, which are themed
    // independently by lib/useTheme.ts based on that setting.
    userInterfaceStyle: 'automatic',
    ios: {
      bundleIdentifier: IOS_BUNDLE_IDENTIFIER,
      supportsTablet: true,
      ...(APPLE_TEAM_ID ? { appleTeamId: APPLE_TEAM_ID } : {}),
      // Shared with the widget target (see targets/widget/expo-target.config.js)
      // so the widget can read the app's selected island from the same App
      // Group UserDefaults suite the app writes to - see lib/widgetSync.ts.
      entitlements: {
        'com.apple.security.application-groups': [IOS_APP_GROUP_ID],
      },
      infoPlist: {
        NSLocationWhenInUseUsageDescription:
          'Used only to improve Qibla compass accuracy. Location is never sent anywhere.',
        // No custom/proprietary encryption beyond standard HTTPS (TLS), which
        // is exempt from export compliance documentation requirements.
        ITSAppUsesNonExemptEncryption: false,
      },
    },
    android: {
      package: ANDROID_PACKAGE,
      adaptiveIcon: {
        backgroundColor: '#011C53',
        foregroundImage: './assets/android-icon-foreground.png',
        backgroundImage: './assets/android-icon-background.png',
        monochromeImage: './assets/android-icon-monochrome.png',
      },
      predictiveBackGestureEnabled: false,
      // Required for React Native's Vibration API (lib/useQiblaAlignment.ts's
      // Qibla-aligned buzz). Declared explicitly rather than relying on it
      // coming along transitively via another package's own manifest.
      permissions: ['android.permission.VIBRATE'],
    },
    web: {
      favicon: './assets/favicon.png',
    },
    plugins: [
      'expo-router',
      'expo-status-bar',
      'expo-background-task',
      'expo-localization',
      'expo-location',
      'expo-font',
      [
        'expo-splash-screen',
        {
          // Light-mode default: the original navy wordmark reads cleanly on
          // this pale lagoon background (lightColors.background). The `dark`
          // variant below is Expo's officially-supported OS-appearance
          // splash override (iOS asset-catalog dark variant / Android
          // values-night) - it's the only way a *native* splash (rendered
          // before JS/AsyncStorage load) can react to appearance at all, so
          // it follows the device's system scheme, not this app's own
          // in-app Appearance setting.
          image: './assets/splash-icon.png',
          backgroundColor: '#E4F4F6',
          imageWidth: 160,
          resizeMode: 'contain',
          dark: {
            // Recolored wordmark (navy -> near-white) - the original asset's
            // text was only ~1.3:1 contrast against this navy background,
            // effectively illegible; see assets/splash-icon-dark.png.
            image: './assets/splash-icon-dark.png',
            backgroundColor: '#011C53',
          },
        },
      ],
      [
        'expo-notifications',
        {
          // Android's status-bar notification icon must be a plain white
          // silhouette on a transparent background - Android ignores color
          // info and derives the shape from the alpha channel only, so
          // pointing this at the full-color launcher icon (as it was)
          // renders as an unrecognizable solid blob rather than the Noor+
          // mark. Reusing the adaptive icon's monochrome layer here since
          // it's already exactly that: the same mark, already prepared as
          // a white-on-transparent silhouette. (iOS always shows the app's
          // actual icon for notifications - there's no separate small icon
          // to configure there.)
          icon: './assets/android-icon-monochrome.png',
          color: '#13E2E6',
          ...(adhanSoundExists ? { sounds: [ADHAN_SOUND_RELATIVE_PATH] } : {}),
        },
      ],
      '@bacons/apple-targets',
      // Must come after Expo's own icon generation (a base mod that always
      // runs before anything in this array) - see the plugin's own comment
      // for why it's needed: fixes the notification icon on unsigned
      // sideload builds.
      './plugins/withFullAppIconSet',
    ],
    experiments: {
      typedRoutes: true,
    },
    extra: {
      iosAppGroupId: IOS_APP_GROUP_ID,
      eas: {
        projectId: '5eec6b7b-3abb-4f79-9a83-d2ca5aa0dfbe',
      },
    },
    owner: 'locallymv',
  },
};
