const fs = require('fs');
const path = require('path');

// Bundle/App Group identifiers are read from env vars (set as GitHub Actions
// secrets/variables in CI) rather than hardcoded, since whoever builds this
// needs to register these under their own Apple ID on the free developer
// portal. Sensible local-dev defaults are provided as fallbacks.
const IOS_BUNDLE_IDENTIFIER = process.env.IOS_BUNDLE_IDENTIFIER || 'com.prayermv.app';
const IOS_APP_GROUP_ID = process.env.IOS_APP_GROUP_ID || `group.${IOS_BUNDLE_IDENTIFIER}`;
const ANDROID_PACKAGE = process.env.ANDROID_PACKAGE || 'com.prayermv.app';
const APPLE_TEAM_ID = process.env.APPLE_TEAM_ID || undefined;

// See assets/sounds/README.md - the actual adhan.wav isn't committed yet,
// so this only gets added to the notifications plugin (which would
// otherwise fail the prebuild trying to copy a file that doesn't exist)
// once someone actually drops it in.
const ADHAN_SOUND_RELATIVE_PATH = './assets/sounds/adhan.wav';
const adhanSoundExists = fs.existsSync(path.join(__dirname, 'assets/sounds/adhan.wav'));

// The widget needs this same App Group id compiled in natively so it can
// open the same UserDefaults suite the app writes its selected island to
// (see lib/widgetSync.ts / targets/widget/PrayerData.swift's
// appSelectedIslandId()) - Swift can't read this JS-side env-derived
// constant any other way, since IOS_APP_GROUP_ID varies per builder's own
// Apple ID. Regenerated on every config read (prebuild/start/export/CI), so
// it can't drift from the entitlement below; not committed (see .gitignore).
fs.writeFileSync(
  path.join(__dirname, 'targets/widget/AppGroupConfig.generated.swift'),
  `// GENERATED by app.config.js from IOS_APP_GROUP_ID - do not edit by hand.\nenum AppGroupConfig {\n    static let identifier = "${IOS_APP_GROUP_ID}"\n}\n`
);

/** @type {import('expo/config').ExpoConfig} */
module.exports = {
  expo: {
    name: 'Noor+',
    slug: 'prayermv',
    version: '1.0.0',
    scheme: 'prayermv',
    orientation: 'portrait',
    icon: './assets/icon.png',
    userInterfaceStyle: 'dark',
    ios: {
      bundleIdentifier: IOS_BUNDLE_IDENTIFIER,
      supportsTablet: true,
      ...(APPLE_TEAM_ID ? { appleTeamId: APPLE_TEAM_ID } : {}),
      // Shared with the widget target (see targets/widget/expo-target.config.js)
      // so the widget can read the app's selected island from the same App
      // Group UserDefaults suite the app writes to - see lib/widgetSync.ts.
      entitlements: {
        'com.apple.security.application-groups': [IOS_APP_GROUP_ID],
      },
      infoPlist: {
        NSLocationWhenInUseUsageDescription:
          'Used only to improve Qibla compass accuracy. Location is never sent anywhere.',
      },
    },
    android: {
      package: ANDROID_PACKAGE,
      adaptiveIcon: {
        backgroundColor: '#011C53',
        foregroundImage: './assets/android-icon-foreground.png',
        backgroundImage: './assets/android-icon-background.png',
        monochromeImage: './assets/android-icon-monochrome.png',
      },
      predictiveBackGestureEnabled: false,
    },
    web: {
      favicon: './assets/favicon.png',
    },
    plugins: [
      'expo-router',
      'expo-status-bar',
      'expo-background-task',
      'expo-localization',
      'expo-location',
      'expo-font',
      [
        'expo-splash-screen',
        {
          image: './assets/splash-icon.png',
          backgroundColor: '#011C53',
          imageWidth: 160,
          resizeMode: 'contain',
        },
      ],
      [
        'expo-notifications',
        {
          icon: './assets/icon.png',
          color: '#13E2E6',
          ...(adhanSoundExists ? { sounds: [ADHAN_SOUND_RELATIVE_PATH] } : {}),
        },
      ],
      '@bacons/apple-targets',
    ],
    experiments: {
      typedRoutes: true,
    },
    extra: {
      iosAppGroupId: IOS_APP_GROUP_ID,
    },
  },
};
