import Foundation

struct RawIsland: Decodable {
    let islandId: Int
    let atollId: Int
    let atoll: String
    let island: String
    let offset: Int
}

struct RawDayEntry: Decodable {
    let atollId: Int
    let day: Int
    let fajr: Int
    let sunrise: Int
    let dhuhr: Int
    let asr: Int
    let maghrib: Int
    let isha: Int
}

struct RawData: Decodable {
    let islands: [RawIsland]
    let atolls: [String: [RawDayEntry]]
}

enum PrayerName: String, CaseIterable {
    case fajr, sunrise, dhuhr, asr, maghrib, isha

    var displayName: String {
        switch self {
        case .fajr: return "Fajr"
        case .sunrise: return "Sunrise"
        case .dhuhr: return "Dhuhr"
        case .asr: return "Asr"
        case .maghrib: return "Maghrib"
        case .isha: return "Isha"
        }
    }

    /// For accessoryCircular, which only has room for a couple of
    /// characters per line.
    var shortName: String {
        switch self {
        case .fajr: return "FAJR"
        case .sunrise: return "SUN"
        case .dhuhr: return "DHUHR"
        case .asr: return "ASR"
        case .maghrib: return "MAGHRIB"
        case .isha: return "ISHA"
        }
    }
}

struct PrayerMoment {
    let name: PrayerName
    let date: Date
    let timeString: String
}

/// Reads the same island-published prayer time data mv-prayertimes ships -
/// every island the app itself can show (see PrayerData.json in this
/// directory, regenerated by scripts/generate-widget-prayer-data.js) - and
/// reimplements its day-of-year lookup, matching lib/prayerTimes.ts in the
/// main app so both sides agree.
enum PrayerData {
    static let raw: RawData = {
        guard
            let url = Bundle.main.url(forResource: "PrayerData", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let decoded = try? JSONDecoder().decode(RawData.self, from: data)
        else {
            return RawData(islands: [], atolls: [:])
        }
        return decoded
    }()

    static func island(for id: Int) -> RawIsland? {
        raw.islands.first { $0.islandId == id }
    }

    /// Fallback if neither the widget's own configuration nor the app's
    /// shared selection can be resolved (e.g. a fresh install, before the
    /// app has ever run and written anything to the App Group).
    static let defaultIslandId = 102 // K. Male'

    private static let selectedIslandKey = "selectedIslandId"

    /// The island id the RN app currently has selected, read from the
    /// shared App Group UserDefaults suite the app writes to via
    /// lib/widgetSync.ts (ExtensionStorage, from @bacons/apple-targets)
    /// whenever the user picks an island. Nil if the app has never written
    /// one yet, or the App Group entitlement isn't available on this build.
    static func appSelectedIslandId() -> Int? {
        guard
            let defaults = UserDefaults(suiteName: AppGroupConfig.identifier),
            defaults.object(forKey: selectedIslandKey) != nil
        else { return nil }
        return defaults.integer(forKey: selectedIslandKey)
    }

    private static func daysIntoYear(_ date: Date) -> Int {
        var utcCalendar = Calendar(identifier: .gregorian)
        utcCalendar.timeZone = TimeZone(identifier: "UTC")!

        let localComponents = Calendar.current.dateComponents([.year, .month, .day], from: date)
        guard
            let target = utcCalendar.date(from: localComponents),
            let jan1 = utcCalendar.date(from: DateComponents(year: localComponents.year, month: 1, day: 1))
        else {
            return 0
        }

        let diffDays = Int(target.timeIntervalSince(jan1) / 86400) + 1
        return diffDays % 366
    }

    private static func minutesValue(_ entry: RawDayEntry, for prayer: PrayerName) -> Int {
        switch prayer {
        case .fajr: return entry.fajr
        case .sunrise: return entry.sunrise
        case .dhuhr: return entry.dhuhr
        case .asr: return entry.asr
        case .maghrib: return entry.maghrib
        case .isha: return entry.isha
        }
    }

    private static func minutesToDate(_ minutesIntoDay: Int, on referenceDate: Date) -> Date {
        var components = Calendar.current.dateComponents([.year, .month, .day], from: referenceDate)
        components.hour = minutesIntoDay / 60
        components.minute = minutesIntoDay % 60
        components.second = 0
        return Calendar.current.date(from: components) ?? referenceDate
    }

    private static func minutesToTimeString(_ minutesIntoDay: Int) -> String {
        String(format: "%02d:%02d", minutesIntoDay / 60, minutesIntoDay % 60)
    }

    private static func entry(for islandId: Int, day: Int) -> RawDayEntry? {
        guard let island = island(for: islandId) else { return nil }
        return raw.atolls[String(island.atollId)]?.first { $0.day == day }
    }

    static func todayMoments(islandId: Int, now: Date = Date()) -> [PrayerMoment] {
        guard
            let island = island(for: islandId),
            let entry = entry(for: islandId, day: daysIntoYear(now))
        else { return [] }

        return PrayerName.allCases.map { prayer in
            let minutes = minutesValue(entry, for: prayer) + island.offset
            return PrayerMoment(
                name: prayer,
                date: minutesToDate(minutes, on: now),
                timeString: minutesToTimeString(minutes)
            )
        }
    }

    /// The next upcoming prayer (or sunrise). Rolls over to tomorrow's Fajr
    /// once every prayer for today has passed.
    static func nextMoment(islandId: Int, now: Date = Date()) -> PrayerMoment? {
        let today = todayMoments(islandId: islandId, now: now)
        if let upcoming = today.first(where: { $0.date > now }) {
            return upcoming
        }

        guard
            let island = island(for: islandId),
            let tomorrow = Calendar.current.date(byAdding: .day, value: 1, to: now),
            let entry = entry(for: islandId, day: (daysIntoYear(now) + 1) % 366)
        else { return nil }

        let minutes = minutesValue(entry, for: .fajr) + island.offset
        return PrayerMoment(
            name: .fajr,
            date: minutesToDate(minutes, on: tomorrow),
            timeString: minutesToTimeString(minutes)
        )
    }
}
